version: "3.8"

networks:
  default:
    external: 
      name: netstreams-controlcenter-infra_default

services:
  netstreams.controlcenter.telemetryprocessor:
    image: telemetry-processor
    build:
      context: ./
      dockerfile: src/NetStreams.ControlCenter/Server/NetStreams.ControlCenter.TelemetryProcessor/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
      - SqlConnectionString=Server=db;Database=NetStreamsControlCenter;User Id=SA;Password=ReallyCoolPassword!;  
    ports:
      - "6101:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro