// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetStreams.ControlCenter.TelemetryProcessor.Infrastructure.EntityFrameworkCore;

namespace NetStreams.ControlCenter.TelemetryProcessor.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetStreams.ControlCenter.TelemetryProcessor.Models.ConsumedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProcessingDurationSeconds")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("StartedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StreamProcessorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumedMessages");
                });

            modelBuilder.Entity("NetStreams.ControlCenter.TelemetryProcessor.Models.StreamPartition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Lag")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.Property<string>("StreamProcessorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StreamProcessorId");

                    b.ToTable("StreamPartitions");
                });

            modelBuilder.Entity("NetStreams.ControlCenter.TelemetryProcessor.Models.StreamProcessor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("LastHeartBeat")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastStarted")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Running")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("StreamProcessors");
                });

            modelBuilder.Entity("NetStreams.ControlCenter.TelemetryProcessor.Models.StreamPartition", b =>
                {
                    b.HasOne("NetStreams.ControlCenter.TelemetryProcessor.Models.StreamProcessor", null)
                        .WithMany("StreamPartitions")
                        .HasForeignKey("StreamProcessorId");
                });

            modelBuilder.Entity("NetStreams.ControlCenter.TelemetryProcessor.Models.StreamProcessor", b =>
                {
                    b.Navigation("StreamPartitions");
                });
#pragma warning restore 612, 618
        }
    }
}
